apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-label
  labels: 
    team: kentang
    version: 2.0
    environment: production
spec:
  containers:
    - name: nginx
      image: nginx
      ports: 
        - containerPorts: 80
