apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    teams: kentang
    version: 2.0
    environtment: production
spec:
  containers:
    - name: nginx
      images: nginx
      ports: 
        - containerPorts: 80
        